/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminEnrollmentsIndexRouteImport } from './routes/admin/enrollments/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminCoursesNewRouteImport } from './routes/admin/courses/new'
import { Route as AdminCoursesSlugEditRouteImport } from './routes/admin/courses/$slug/edit'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnrollmentsIndexRoute = AdminEnrollmentsIndexRouteImport.update({
  id: '/enrollments/',
  path: '/enrollments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesSlugEditRoute = AdminCoursesSlugEditRouteImport.update({
  id: '/courses/$slug/edit',
  path: '/courses/$slug/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/enrollments/': typeof AdminEnrollmentsIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/courses/$slug/edit': typeof AdminCoursesSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/enrollments': typeof AdminEnrollmentsIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/courses/$slug/edit': typeof AdminCoursesSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/enrollments/': typeof AdminEnrollmentsIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/courses/$slug/edit': typeof AdminCoursesSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/courses/new'
    | '/admin/courses/'
    | '/admin/dashboard/'
    | '/admin/enrollments/'
    | '/admin/students/'
    | '/admin/courses/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/courses/new'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/students'
    | '/admin/courses/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/courses/new'
    | '/admin/courses/'
    | '/admin/dashboard/'
    | '/admin/enrollments/'
    | '/admin/students/'
    | '/admin/courses/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enrollments/': {
      id: '/admin/enrollments/'
      path: '/enrollments'
      fullPath: '/admin/enrollments/'
      preLoaderRoute: typeof AdminEnrollmentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/$slug/edit': {
      id: '/admin/courses/$slug/edit'
      path: '/courses/$slug/edit'
      fullPath: '/admin/courses/$slug/edit'
      preLoaderRoute: typeof AdminCoursesSlugEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminEnrollmentsIndexRoute: typeof AdminEnrollmentsIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminCoursesSlugEditRoute: typeof AdminCoursesSlugEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminEnrollmentsIndexRoute: AdminEnrollmentsIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminCoursesSlugEditRoute: AdminCoursesSlugEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
